#!/bin/bash

if [[ $# -eq 1 ]] ; then
    echo 'building a Superset release...'
    gradle build
    ENV_ID=$1
fi

if [[ $# -lt 1 ]] ; then
    echo 'usage pushdist [RELEASE NUMBER]...'
    exit 1
fi


cd dockerbuild
sudo docker build -t  registry.b2w.io/b2wdigital/superset-b2w:$ENV_ID .
# sudo docker push  registry.b2w.io/b2wdigital/superset-b2w:$ENV_ID
